import type { DoHProvider } from '@/types';

/**
 * Comprehensive list of 28 DoH providers for benchmarking.
 *
 * CORS support column:
 *   ✅ = confirmed browser CORS support (measured directly from browser)
 *   ⚠️ = CORS may be blocked on some origins (proxy fallback used automatically)
 */
export const DOH_PROVIDERS: DoHProvider[] = [
  // ── Cloudflare ───────────────────────────────────────────────────────────────
  {
    id: 'cloudflare',
    name: 'Cloudflare 1.1.1.1',
    shortName: 'Cloudflare',
    dohUrl: 'https://cloudflare-dns.com/dns-query',
    color: '#f48120',
    description: 'The fastest public DNS resolver (1.1.1.1). Privacy-first, no logging.',
    privacyUrl: 'https://developers.cloudflare.com/1.1.1.1/privacy/',
    dnssec: true,
    filtering: 'none',
    country: 'US',
  },
  {
    id: 'cloudflare-security',
    name: 'Cloudflare Security',
    shortName: 'CF Security',
    dohUrl: 'https://security.cloudflare-dns.com/dns-query',
    color: '#f48120',
    description: 'Cloudflare 1.1.1.2 — blocks malware & phishing domains.',
    privacyUrl: 'https://developers.cloudflare.com/1.1.1.1/privacy/',
    dnssec: true,
    filtering: 'malware',
    country: 'US',
  },
  {
    id: 'cloudflare-family',
    name: 'Cloudflare Family',
    shortName: 'CF Family',
    dohUrl: 'https://family.cloudflare-dns.com/dns-query',
    color: '#f48120',
    description: 'Cloudflare 1.1.1.3 — blocks malware & adult content.',
    privacyUrl: 'https://developers.cloudflare.com/1.1.1.1/privacy/',
    dnssec: true,
    filtering: 'family',
    country: 'US',
  },

  // ── Google ────────────────────────────────────────────────────────────────────
  {
    id: 'google',
    name: 'Google Public DNS',
    shortName: 'Google',
    dohUrl: 'https://dns.google/dns-query',
    color: '#4285F4',
    description: 'Google\'s global public DNS (8.8.8.8). High reliability, DNSSEC validated.',
    privacyUrl: 'https://developers.google.com/speed/public-dns/privacy',
    dnssec: true,
    filtering: 'none',
    country: 'US',
  },

  // ── Quad9 ─────────────────────────────────────────────────────────────────────
  {
    id: 'quad9',
    name: 'Quad9 (Secured)',
    shortName: 'Quad9',
    dohUrl: 'https://dns.quad9.net/dns-query',
    color: '#C02020',
    description: 'Non-profit resolver with threat intelligence from 25+ partners. DNSSEC validated.',
    privacyUrl: 'https://www.quad9.net/privacy/policy/',
    dnssec: true,
    filtering: 'malware',
    country: 'CH',
  },
  {
    id: 'quad9-unsecured',
    name: 'Quad9 (Open)',
    shortName: 'Quad9 Open',
    dohUrl: 'https://dns9.quad9.net/dns-query',
    color: '#C02020',
    description: 'Quad9 without threat blocking. DNSSEC validated.',
    privacyUrl: 'https://www.quad9.net/privacy/policy/',
    dnssec: true,
    filtering: 'none',
    country: 'CH',
  },

  // ── CIRA Canadian Shield ──────────────────────────────────────────────────────
  {
    id: 'canadian-shield-private',
    name: 'Canadian Shield Private',
    shortName: 'CA Shield',
    dohUrl: 'https://private.canadianshield.cira.ca/dns-query',
    color: '#FF0000',
    description: 'CIRA\'s Canadian Shield — no filtering, operated in Canada. Privacy-focused.',
    privacyUrl: 'https://www.cira.ca/en/canadian-shield/privacy',
    dnssec: true,
    filtering: 'none',
    country: 'CA',
  },
  {
    id: 'canadian-shield-protected',
    name: 'Canadian Shield Protected',
    shortName: 'CA Protected',
    dohUrl: 'https://protected.canadianshield.cira.ca/dns-query',
    color: '#FF0000',
    description: 'CIRA\'s Canadian Shield — blocks malware & phishing. Data stays in Canada.',
    privacyUrl: 'https://www.cira.ca/en/canadian-shield/privacy',
    dnssec: true,
    filtering: 'malware',
    country: 'CA',
  },
  {
    id: 'canadian-shield-family',
    name: 'Canadian Shield Family',
    shortName: 'CA Family',
    dohUrl: 'https://family.canadianshield.cira.ca/dns-query',
    color: '#FF0000',
    description: 'CIRA\'s Canadian Shield — blocks malware & adult content for families.',
    privacyUrl: 'https://www.cira.ca/en/canadian-shield/privacy',
    dnssec: true,
    filtering: 'family',
    country: 'CA',
  },

  // ── Privacy-Focused ───────────────────────────────────────────────────────────
  {
    id: 'mullvad',
    name: 'Mullvad DNS',
    shortName: 'Mullvad',
    dohUrl: 'https://dns.mullvad.net/dns-query',
    color: '#44AD8E',
    description: 'No-log DNS by Mullvad VPN. Based in Sweden.',
    privacyUrl: 'https://mullvad.net/help/dns-over-https-and-dns-over-tls/',
    dnssec: true,
    filtering: 'none',
    country: 'SE',
  },
  {
    id: 'nextdns',
    name: 'NextDNS',
    shortName: 'NextDNS',
    dohUrl: 'https://dns.nextdns.io/dns-query',
    color: '#1a73e8',
    description: 'Fully configurable privacy-first DNS with analytics & custom lists.',
    privacyUrl: 'https://nextdns.io/privacy',
    dnssec: true,
    filtering: 'ads+malware',
    country: 'US',
  },
  {
    id: 'adguard',
    name: 'AdGuard DNS',
    shortName: 'AdGuard',
    dohUrl: 'https://dns.adguard-dns.com/dns-query',
    color: '#68BC71',
    description: 'Ad & tracker blocking DNS from AdGuard.',
    privacyUrl: 'https://adguard-dns.io/en/privacy.html',
    dnssec: true,
    filtering: 'ads+malware',
    country: 'CY',
  },
  {
    id: 'adguard-unfiltered',
    name: 'AdGuard (Open)',
    shortName: 'AdGuard Open',
    dohUrl: 'https://unfiltered.adguard-dns.com/dns-query',
    color: '#68BC71',
    description: 'AdGuard DNS without any blocking.',
    privacyUrl: 'https://adguard-dns.io/en/privacy.html',
    dnssec: true,
    filtering: 'none',
    country: 'CY',
  },
  {
    id: 'controld',
    name: 'ControlD (Free)',
    shortName: 'ControlD',
    dohUrl: 'https://freedns.controld.com/p0',
    color: '#7C3AED',
    description: 'Highly configurable DNS proxy with custom rules.',
    privacyUrl: 'https://controld.com/privacy-policy',
    dnssec: true,
    filtering: 'none',
    country: 'CA',
  },
  {
    id: 'rethinkdns',
    name: 'RethinkDNS',
    shortName: 'Rethink',
    dohUrl: 'https://sky.rethinkdns.com/dns-query',
    color: '#4F46E5',
    description: 'Open-source, configurable DoH resolver. Serverless architecture.',
    privacyUrl: 'https://rethinkdns.com/privacy',
    dnssec: true,
    filtering: 'none',
    country: 'US',
  },
  {
    id: 'libredns',
    name: 'LibreDNS',
    shortName: 'LibreDNS',
    dohUrl: 'https://doh.libredns.gr/dns-query',
    color: '#EF4444',
    description: 'Free, open, non-logging DoH by the LibreOps community. Based in Germany.',
    privacyUrl: 'https://libredns.gr/',
    dnssec: false,
    filtering: 'none',
    country: 'DE',
  },
  {
    id: 'dnssb',
    name: 'DNS.SB',
    shortName: 'DNS.SB',
    dohUrl: 'https://doh.dns.sb/dns-query',
    color: '#9333EA',
    description: 'Privacy-focused, DNSSEC-enabled anycast resolver.',
    privacyUrl: 'https://dns.sb/privacy/',
    dnssec: true,
    filtering: 'none',
    country: 'DE',
  },

  // ── Cisco / Enterprise ────────────────────────────────────────────────────────
  {
    id: 'opendns-home',
    name: 'OpenDNS Home',
    shortName: 'OpenDNS',
    dohUrl: 'https://doh.opendns.com/dns-query',
    color: '#1aa0d8',
    description: 'Cisco\'s OpenDNS — phishing & botnet protection.',
    privacyUrl: 'https://www.opendns.com/data-privacy/',
    dnssec: false,
    filtering: 'malware',
    country: 'US',
  },
  {
    id: 'opendns-family',
    name: 'OpenDNS FamilyShield',
    shortName: 'OD Family',
    dohUrl: 'https://doh.familyshield.opendns.com/dns-query',
    color: '#1aa0d8',
    description: 'OpenDNS with adult content blocking enabled (208.67.222.123).',
    privacyUrl: 'https://www.opendns.com/data-privacy/',
    dnssec: false,
    filtering: 'family',
    country: 'US',
  },
  {
    id: 'cisco-umbrella',
    name: 'Cisco Umbrella',
    shortName: 'Umbrella',
    dohUrl: 'https://doh.umbrella.com/dns-query',
    color: '#00BCEB',
    description: 'Cisco Umbrella cloud security. Enterprise-grade threat intelligence.',
    privacyUrl: 'https://umbrella.cisco.com/why-umbrella/global-network-and-traffic',
    dnssec: false,
    filtering: 'malware',
    country: 'US',
  },

  // ── Security / Family Filtering ───────────────────────────────────────────────
  {
    id: 'cleanbrowsing-security',
    name: 'CleanBrowsing Security',
    shortName: 'CB Security',
    dohUrl: 'https://doh.cleanbrowsing.org/doh/security-filter/',
    color: '#0EA5E9',
    description: 'Blocks malware, phishing, and cryptojacking domains.',
    privacyUrl: 'https://cleanbrowsing.org/privacy',
    dnssec: false,
    filtering: 'malware',
    country: 'US',
  },
  {
    id: 'cleanbrowsing-family',
    name: 'CleanBrowsing Family',
    shortName: 'CB Family',
    dohUrl: 'https://doh.cleanbrowsing.org/doh/family-filter/',
    color: '#0EA5E9',
    description: 'Blocks adult content, malware & mixed content.',
    privacyUrl: 'https://cleanbrowsing.org/privacy',
    dnssec: false,
    filtering: 'family',
    country: 'US',
  },

  // ── Regional / ISP-Alternative ────────────────────────────────────────────────
  {
    id: 'dnspod',
    name: 'DNSPod (Tencent)',
    shortName: 'DNSPod',
    dohUrl: 'https://doh.pub/dns-query',
    color: '#0052D9',
    description: 'Tencent\'s high-performance DoH resolver.',
    privacyUrl: 'https://www.dnspod.cn/',
    dnssec: false,
    filtering: 'none',
    country: 'CN',
  },
  {
    id: 'alidns',
    name: 'AliDNS (Alibaba)',
    shortName: 'AliDNS',
    dohUrl: 'https://dns.alidns.com/dns-query',
    color: '#FF6A00',
    description: 'Alibaba Cloud public DNS resolver (223.5.5.5).',
    privacyUrl: 'https://www.alidns.com/',
    dnssec: false,
    filtering: 'none',
    country: 'CN',
  },
  {
    id: 'hurricane-electric',
    name: 'Hurricane Electric',
    shortName: 'HurricaneE',
    dohUrl: 'https://ordns.he.net/dns-query',
    color: '#1E40AF',
    description: 'Free DoH resolver by Hurricane Electric, one of the world\'s largest IPv6 networks.',
    privacyUrl: 'https://dns.he.net/',
    dnssec: true,
    filtering: 'none',
    country: 'US',
  },
  {
    id: 'dnsforge',
    name: 'DNS Forge (DE)',
    shortName: 'DNS Forge',
    dohUrl: 'https://dnsforge.de/dns-query',
    color: '#059669',
    description: 'Ad-blocking DoH resolver operated in Germany. No logging.',
    privacyUrl: 'https://dnsforge.de/',
    dnssec: true,
    filtering: 'ads+malware',
    country: 'DE',
  },
  {
    id: 'switch',
    name: 'SWITCH.ch DNS',
    shortName: 'SWITCH',
    dohUrl: 'https://dns.switch.ch/dns-query',
    color: '#CC0000',
    description: 'Swiss academic network resolver with malware blocking. DNSSEC validated.',
    privacyUrl: 'https://www.switch.ch/security/info/public-dns/',
    dnssec: true,
    filtering: 'malware',
    country: 'CH',
  },
  {
    id: 'comodo',
    name: 'Comodo Secure DNS',
    shortName: 'Comodo',
    dohUrl: 'https://doh.comodo.com/dns-query',
    color: '#E84444',
    description: 'Comodo\'s secure DNS with malware & phishing protection.',
    privacyUrl: 'https://www.comodo.com/home/internet-security/secure-dns.php',
    dnssec: false,
    filtering: 'malware',
    country: 'US',
  },
  {
    id: 'yandex',
    name: 'Yandex DNS',
    shortName: 'Yandex',
    dohUrl: 'https://common.dot.dns.yandex.net/dns-query',
    color: '#FFCC00',
    description: 'Yandex\'s public resolver — fast for Eastern Europe and Russia.',
    privacyUrl: 'https://dns.yandex.com/',
    dnssec: false,
    filtering: 'none',
    country: 'RU',
  },
];

export default DOH_PROVIDERS;
