import type { ProviderReview } from '@/types';

/**
 * Authentic, technical reviews of each DNS provider.
 * Providers with multiple tiers are consolidated into a single brand review.
 */
export const PROVIDER_REVIEWS: Record<string, ProviderReview> = {

  // ── Cloudflare ───────────────────────────────────────────────────────────────
  cloudflare: {
    providerId: 'cloudflare',
    reviewTitle: 'Cloudflare',
    editorialScore: 8.7,
    tagline: 'The undisputed speed champion, though anycast routing can occasionally misbehave.',
    summary: "Cloudflare is the default choice for most tech-savvy users wanting raw speed. Leveraging their massive CDN infrastructure, they consistently top global speed benchmarks. However, sysadmins frequently note that specific ISP peering arrangements can sometimes break their anycast routing, sending traffic to a PoP a continent away.",
    privacyDetail: "KPMG audits their 24-hour log purge policy, which is a rare level of accountability. They do QNAME minimization properly. However, they are a massive US corporation subject to FISA. Private enough for most, but purists look elsewhere.",
    performanceDetail: "Raw latency is unmatched in most regions. That said, 'fastest on average' doesn't mean fastest for *you*. If your ISP has poor peering with Cloudflare, your latency will spike.",
    securityDetail: "Security depends entirely on the tier chosen. 1.1.1.1 is an unfiltered 'dumb pipe', while the Security and Family variants passively block known malicious domains without giving you the ability to whitelist.",
    pros: ['Unmatched raw speed globally', 'KPMG privacy audits', 'Excellent DoH/DoT/DoQ support'],
    cons: ['Anycast routing can act up with certain ISPs', 'US jurisdiction', 'No whitelisting on filtered tiers'],
    bestFor: ['Gamers and speed-chasers', 'Users wanting a fast, reliable set-and-forget pipe'],
    worstFor: ['Users experiencing local Cloudflare peering issues', 'Privacy absolutists'],
    verdict: "The standard recommendation for speed and reliability across all its tiers. Just ensure your ISP routes to them efficiently. If pure privacy is the goal, Quad9 or Mullvad are better bets.",
    lastUpdated: '2026-06-01',
    tiers: [
      { name: '1.1.1.1 (Base)', description: 'Raw speed. Unfiltered resolution with DNSSEC validation.' },
      { name: '1.1.1.2 (Security)', description: 'Blocks known malware and phishing domains using Cloudflare threat intel.' },
      { name: '1.1.1.3 (Family)', description: 'Blocks malware and adult content. Broad and lacks granular whitelisting.' }
    ]
  },

  // ── Google ────────────────────────────────────────────────────────────────────
  google: {
    providerId: 'google',
    editorialScore: 7.0,
    tagline: "Rock solid and globally pervasive, but you're feeding the data machine.",
    summary: "8.8.8.8 is the most famous DNS resolver on earth. It is practically bulletproof in terms of uptime. But in tech circles, using it is increasingly seen as an unnecessary privacy concession.",
    privacyDetail: "Google claims they don't correlate DNS queries with ad targeting. However, they do retain aggregate data. No independent privacy audits exist.",
    performanceDetail: "Incredible. In emerging markets (Africa, Southeast Asia), Google often beats Cloudflare simply because their infrastructure footprint is deeper.",
    securityDetail: "Validates DNSSEC, but offers zero threat filtering. It will happily resolve a known malware domain.",
    pros: ['Essentially 100% uptime', 'Incredible performance in emerging markets'],
    cons: ['Massive privacy concerns', 'Contributes to Google internet monopoly', 'No filtering'],
    bestFor: ['Diagnosing network issues', 'Users in remote regions'],
    worstFor: ['Anyone who cares about privacy', 'Users wanting malware protection'],
    verdict: "The ultimate fallback resolver. But for daily driving, there is no technical reason to choose Google over Cloudflare or Quad9, and several privacy reasons not to.",
    lastUpdated: '2026-06-01',
  },

  // ── Quad9 ─────────────────────────────────────────────────────────────────────
  quad9: {
    providerId: 'quad9',
    reviewTitle: 'Quad9',
    editorialScore: 9.2,
    tagline: "The sysadmin's choice for privacy and security, despite occasional routing hiccups.",
    summary: "Quad9 operates as a Swiss non-profit, aggregating threat intelligence from dozens of vendors to block malware, while strictly refusing to log user data.",
    privacyDetail: "The gold standard. Swiss jurisdiction gives them massive legal cover, and their non-profit status removes monetization incentives. No IP logging.",
    performanceDetail: "Anycast routing is notoriously finicky—some users get 10ms latency, while others get routed to a different country resulting in 80ms+. You must test it locally.",
    securityDetail: "Incredible threat blocking on their default tier. Because they aggregate lists from IBM, Proofpoint, and others, they block things others miss. False positives happen, but are rare.",
    pros: ['Unbeatable privacy stance', 'Top-tier threat intelligence', 'No IP logging'],
    cons: ['Inconsistent anycast routing depending on your ISP', 'Higher baseline latency than Cloudflare'],
    bestFor: ['Privacy advocates', 'Security-conscious home networks', 'European users'],
    worstFor: ['Users whose ISP routes Quad9 poorly', 'Gamers needing absolute minimum latency'],
    verdict: "The most highly respected public resolver among security professionals. If your ISP routes to them efficiently, it is the best daily driver available.",
    lastUpdated: '2026-06-01',
    tiers: [
      { name: 'Secured (9.9.9.9)', description: 'The flagship offering. Blocks malware, phishing, and botnets using aggregated threat intel.' },
      { name: 'Open (9.9.9.10)', description: 'Unfiltered resolution with the same strict Swiss privacy guarantees. Used primarily for troubleshooting.' }
    ]
  },

  // ── CIRA Canadian Shield ──────────────────────────────────────────────────────
  'canadian-shield-private': {
    providerId: 'canadian-shield-private',
    reviewTitle: 'CIRA Canadian Shield',
    editorialScore: 8.4,
    tagline: "Phenomenal for Canadians; completely irrelevant for everyone else.",
    summary: "Run by CIRA, Canadian Shield ensures your DNS traffic never leaves Canada. It offers three distinct tiers sharing the same excellent localized infrastructure.",
    privacyDetail: "Excellent for Canadians. Protected by PIPEDA, data stays within Canada, out of reach of the US Patriot Act/FISA. Non-profit operation.",
    performanceDetail: "Lightning fast if you live in Toronto or Vancouver. Terribly slow if you live in London or Tokyo. The infrastructure is intentionally localized.",
    securityDetail: "Security scales from zero filtering to adult-content blocking depending on the selected tier. DNSSEC is standard across all.",
    pros: ['True data sovereignty for Canadians', 'Non-profit operator', 'Great local peering'],
    cons: ['Useless outside Canada', 'Lacks granular whitelisting'],
    bestFor: ['Canadians wanting sovereignty', 'Canadian businesses needing PIPEDA compliance'],
    worstFor: ['Anyone not in Canada'],
    verdict: "If you live in Canada, this should be on your shortlist. It provides excellent local routing with a tier for every basic network need.",
    lastUpdated: '2026-06-01',
    tiers: [
      { name: 'Private', description: 'Maximum speed, unfiltered resolution.' },
      { name: 'Protected', description: 'Adds malware and phishing domain blocking.' },
      { name: 'Family', description: 'Adds broad adult content blocking. Known to occasionally over-block without recourse.' }
    ]
  },

  // ── Privacy / Configurable ────────────────────────────────────────────────────
  mullvad: {
    providerId: 'mullvad',
    editorialScore: 8.9,
    tagline: "Absolute, unquestioned privacy. The paranoid sysadmin's choice.",
    summary: "Mullvad operates with a fanatical devotion to privacy. Their DNS resolver is an extension of their VPN philosophy: absolutely no logs, no analytics, no BS.",
    privacyDetail: "Flawless. Swedish jurisdiction. They have been raided by police and had nothing to hand over. They don't even require an email address to use their paid VPN.",
    performanceDetail: "Slower than the giants. They don't have a massive global CDN, so routing can be inefficient outside of Europe and North America.",
    securityDetail: "Basic DoH/DoT with DNSSEC. Simple and effective.",
    pros: ['The most trusted name in privacy', 'Swedish jurisdiction', 'Audited, zero-log infrastructure'],
    cons: ['Higher latency than Cloudflare', 'Fewer global PoPs'],
    bestFor: ['Privacy absolutists', 'Journalists', 'Anyone tired of corporate data harvesting'],
    worstFor: ['Speed obsessives'],
    verdict: "If privacy is your absolute number one priority, use Mullvad. You might lose 15ms on your DNS resolution, but you gain peace of mind.",
    lastUpdated: '2026-06-01',
  },
  nextdns: {
    providerId: 'nextdns',
    editorialScore: 9.0,
    tagline: "Pi-hole in the cloud. Brilliant tech, but the free tier vanishes instantly.",
    summary: "NextDNS is beloved by power users. It offers unprecedented control, allowing you to choose exactly which blocklists to apply, view real-time logs, and set per-device profiles.",
    privacyDetail: "Solid, but US-based. Logs are highly configurable—you can store them in Switzerland or disable them entirely.",
    performanceDetail: "Very good. They use a mix of anycast and geolocation routing with excellent global coverage.",
    securityDetail: "Unmatched. You can enable specific lists like OISD, Energized, or strict parental controls.",
    pros: ['Incredible customizability', 'Replaces local Pi-hole/AdGuard Home setups', 'Great analytics dashboard'],
    cons: ['Free tier (300k queries) is exhausted in days on a modern home network', 'US jurisdiction'],
    bestFor: ['Power users', 'Parents needing strict control', 'Network admins'],
    worstFor: ['Users wanting a free set-it-and-forget-it solution'],
    verdict: "NextDNS is the best configurable DNS service on the market. However, treat it as a paid product ($2/mo).",
    lastUpdated: '2026-06-01',
  },
  adguard: {
    providerId: 'adguard',
    reviewTitle: 'AdGuard',
    editorialScore: 8.2,
    tagline: "Excellent ad-blocking, though corporate history gives some users pause.",
    summary: "AdGuard provides excellent, out-of-the-box ad and tracker blocking. Their filter lists are legendary.",
    privacyDetail: "Currently headquartered in Cyprus (EU/GDPR), but the company has Russian origins. While they have a strict no-logging policy, this history makes strict privacy advocates cautious.",
    performanceDetail: "Generally excellent in Europe and North America. Their anycast network is robust.",
    securityDetail: "Top-tier ad and tracker blocking. Less focused on pure malware than Quad9, but fantastic at cleaning up the modern web.",
    pros: ['Superb ad-blocking lists', 'Free and easy to deploy', 'Good performance'],
    cons: ['Corporate origins cause debate in privacy circles', 'Can break some affiliate links'],
    bestFor: ['Users wanting network-wide ad-blocking without configuring NextDNS'],
    worstFor: ['Extreme privacy purists'],
    verdict: "From a purely technical standpoint, AdGuard DNS works beautifully for wiping out ads at the router level.",
    lastUpdated: '2026-06-01',
    tiers: [
      { name: 'Default', description: 'Robust ad, tracker, and malicious domain blocking based on AdGuard lists.' },
      { name: 'Unfiltered', description: 'Fast, unfiltered resolution using AdGuard infrastructure. Useful for troubleshooting.' }
    ]
  },
  controld: {
    providerId: 'controld',
    editorialScore: 8.4,
    tagline: "The modern challenger to NextDNS with unique geo-unblocking tricks.",
    summary: "Created by the team behind Windscribe VPN, ControlD is gaining serious traction. It offers NextDNS-style filtering with the unique ability to proxy specific domains through different countries.",
    privacyDetail: "Canadian jurisdiction. The free tier (which we test here) is completely no-log.",
    performanceDetail: "The most common complaint on forums is that their anycast network isn't quite as mature as Cloudflare or NextDNS yet. Occasional routing hiccups occur.",
    securityDetail: "The free 'p0' tier is unfiltered. Premium tiers offer exhaustive blocking and proxy rules.",
    pros: ['Innovative geo-proxying (Premium)', 'Canadian privacy laws', 'Clean UI'],
    cons: ['Anycast routing still maturing', 'Free tier lacks the cool features'],
    bestFor: ['Windscribe users', 'Tinkerers wanting geo-unblocking without a full VPN'],
    worstFor: ['Users needing absolute lowest latency'],
    verdict: "ControlD is the most exciting new player in the DNS space. Their routing network is still growing, but their feature set is incredibly innovative.",
    lastUpdated: '2026-06-01',
  },
  rethinkdns: {
    providerId: 'rethinkdns',
    editorialScore: 8.1,
    tagline: "Fascinating serverless architecture that makes logging impossible.",
    summary: "RethinkDNS runs on Cloudflare Workers. It's a clever technical hack: because it's serverless, there's no underlying operating system or database to write logs to.",
    privacyDetail: "Architecturally excellent. Open source and serverless. You are trusting Cloudflare's edge network, but Rethink itself holds no state.",
    performanceDetail: "Relies on Cloudflare's network, so speed is generally excellent.",
    securityDetail: "Highly configurable via URL parameters, allowing you to mash up different blocklists.",
    pros: ['Serverless privacy model', 'Cloudflare-backed speed', 'Open source'],
    cons: ['Configuration via URL is clunky'],
    bestFor: ['Tech enthusiasts', 'Users who like architectural privacy guarantees'],
    worstFor: ['Users wanting a clean GUI dashboard'],
    verdict: "A brilliant proof-of-concept that works great in reality. It's for nerds, by nerds.",
    lastUpdated: '2026-06-01',
  },
  libredns: {
    providerId: 'libredns',
    editorialScore: 7.7,
    tagline: "A genuine grassroots project for the decentralized web.",
    summary: "Run by the LibreOps community, this is a truly independent, open-source DNS resolver. It's a favorite among decentralization advocates.",
    privacyDetail: "Operates out of Germany with strict no-logging policies. Maximum community trust.",
    performanceDetail: "Latency is higher globally because they do not utilize massive corporate anycast networks.",
    securityDetail: "Unfiltered, standard resolution.",
    pros: ['Grassroots, community-run', 'German privacy laws', 'Completely open'],
    cons: ['Poor performance outside Europe', 'No anycast scaling'],
    bestFor: ['Open-source advocates', 'European users'],
    worstFor: ['Global users seeking performance'],
    verdict: "If you want to support independent internet infrastructure and live in Europe, LibreDNS is fantastic. Otherwise, the latency tradeoff is steep.",
    lastUpdated: '2026-06-01',
  },
  dnssb: {
    providerId: 'dnssb',
    editorialScore: 7.6,
    tagline: "A quiet, capable alternative with surprisingly good global routing.",
    summary: "DNS.SB is a privacy-focused resolver that utilizes anycast routing to provide better global latency than many independent projects.",
    privacyDetail: "No-logging policy, based in Germany. Well regarded in privacy communities.",
    performanceDetail: "Surprisingly good. They lease nodes in many locations, providing better average latency than typical single-region indie resolvers.",
    securityDetail: "Standard DNSSEC, unfiltered.",
    pros: ['Good anycast coverage for an indie project', 'German privacy jurisdiction'],
    cons: ['Less institutional backing than Quad9'],
    bestFor: ['Users wanting an indie resolver with decent speeds'],
    worstFor: ['Enterprise users'],
    verdict: "A solid middle ground between massive corporate resolvers and slow single-node indie projects.",
    lastUpdated: '2026-06-01',
  },

  // ── OpenDNS / Cisco ─────────────────────────────────────────────────────────
  'opendns-home': {
    providerId: 'opendns-home',
    reviewTitle: 'OpenDNS (Cisco)',
    editorialScore: 6.5,
    tagline: "A legacy giant that logs too much for modern privacy standards.",
    summary: "OpenDNS was the pioneer of filtered DNS. While the tech works, the modern sysadmin consensus is that it's an outdated choice for personal use due to Cisco's data practices.",
    privacyDetail: "Poor. Cisco uses query data to feed its enterprise threat intelligence network. You are the product.",
    performanceDetail: "Highly reliable with a massive, mature global network. Rarely goes down.",
    securityDetail: "Good phishing protection, but lacks modern ad/tracker blocking.",
    pros: ['Extremely reliable', 'Good legacy phishing protection'],
    cons: ['Heavy logging', 'Cisco corporate data harvesting', 'No DNSSEC validation'],
    bestFor: ['Legacy enterprise deployments'],
    worstFor: ['Privacy-aware home users'],
    verdict: "There is virtually no reason to use OpenDNS for a home network today. Quad9 does threat blocking better with actual privacy.",
    lastUpdated: '2026-06-01',
    tiers: [
      { name: 'Home', description: 'Standard resolution with legacy botnet and phishing protection.' },
      { name: 'FamilyShield', description: 'Enforces adult content blocking. Reliable but lacks granular whitelisting.' }
    ]
  },
  'cisco-umbrella': {
    providerId: 'cisco-umbrella',
    editorialScore: 6.0,
    tagline: "An enterprise behemoth that has no business on a personal network.",
    summary: "This is Cisco's paid enterprise tier. If you're testing this at home, you're either a network admin testing a corporate rollout, or you've made a configuration error.",
    privacyDetail: "Non-existent for the end-user. Designed to log, audit, and restrict employee traffic.",
    performanceDetail: "Enterprise-grade reliability and speed.",
    securityDetail: "World-class enterprise threat intelligence.",
    pros: ['Enterprise SLA', 'Massive threat database'],
    cons: ['Designed for surveillance and compliance, not privacy', 'Overkill for home'],
    bestFor: ['Fortune 500 IT departments'],
    worstFor: ['Literally anyone else'],
    verdict: "Great for corporate compliance; terrible for personal freedom. Do not use at home.",
    lastUpdated: '2026-06-01',
  },

  // ── CleanBrowsing ─────────────────────────────────────────────────────────────
  'cleanbrowsing-security': {
    providerId: 'cleanbrowsing-security',
    reviewTitle: 'CleanBrowsing',
    editorialScore: 8.0,
    tagline: "A dedicated filtering network with transparent tiers.",
    summary: "CleanBrowsing is highly respected for its strict filtering capabilities. They operate Security, Family, and Adult tiers to fit different household needs.",
    privacyDetail: "Solid. US-based but operates with a strong pro-privacy, no-logging manifesto.",
    performanceDetail: "Anycast network provides decent speed, though slightly higher latency than Cloudflare.",
    securityDetail: "Aggressive and accurate threat filtering depending on the tier.",
    pros: ['Transparent filtering rules', 'Good privacy policy'],
    cons: ['Less global coverage than the giants'],
    bestFor: ['Users wanting a dedicated filtering service without NextDNS complexity'],
    worstFor: ['Raw speed enthusiasts'],
    verdict: "A very solid, privacy-respecting alternative to OpenDNS or Cloudflare Family.",
    lastUpdated: '2026-06-01',
    tiers: [
      { name: 'Security', description: 'Blocks malware, phishing, and malicious domains. Does not block adult content.' },
      { name: 'Family', description: 'Blocks malware, adult content, and aggressively enforces Safe Search.' },
      { name: 'Adult', description: 'A middle ground that blocks explicit content but doesn\'t enforce Safe Search.' }
    ]
  },

  // ── Regional / Alternative ────────────────────────────────────────────────────
  dnspod: {
    providerId: 'dnspod',
    editorialScore: 4.5,
    tagline: "Tencent's resolver. Excellent in China, avoid elsewhere.",
    summary: "DNSPod resolves Chinese CDNs perfectly, but carries the baggage of PRC jurisdiction and Tencent's data policies.",
    privacyDetail: "Subject to Chinese data laws. No privacy guarantees for western users.",
    performanceDetail: "Essential for users behind the Great Firewall. Slow and poorly routed in the West.",
    securityDetail: "Basic resolution, subject to local censorship requirements.",
    pros: ['Fixes routing issues for Chinese internet assets'],
    cons: ['PRC jurisdiction', 'Censorship'],
    bestFor: ['Users in mainland China'],
    worstFor: ['Privacy-conscious western users'],
    verdict: "A geographic necessity for some, a privacy nightmare for others.",
    lastUpdated: '2026-06-01',
  },
  alidns: {
    providerId: 'alidns',
    editorialScore: 4.5,
    tagline: "Alibaba's public DNS. Same rules as DNSPod.",
    summary: "Alibaba's equivalent to Google Public DNS. Massive inside China, generally avoided outside due to data sovereignty concerns.",
    privacyDetail: "Subject to PRC data laws. No anonymity guarantees.",
    performanceDetail: "Lightning fast in Asia. Often routes bizarrely in the Americas.",
    securityDetail: "Subject to local censorship blocks.",
    pros: ['Excellent peering with Asian CDNs'],
    cons: ['PRC jurisdiction', 'Censorship'],
    bestFor: ['Alibaba Cloud users', 'Users in mainland China'],
    worstFor: ['Western users'],
    verdict: "Use it if you live in the region and need the peering. Avoid otherwise.",
    lastUpdated: '2026-06-01',
  },
  'hurricane-electric': {
    providerId: 'hurricane-electric',
    editorialScore: 7.2,
    tagline: "The backbone provider's quiet, reliable DNS.",
    summary: "Hurricane Electric runs a massive chunk of the internet's IPv6 backbone. Their DNS isn't flashy, but network engineers respect it.",
    privacyDetail: "Standard US corporate policy. No audited guarantees.",
    performanceDetail: "Great peering because HE *is* the peer for many networks.",
    securityDetail: "Raw DNSSEC, no filtering.",
    pros: ['Incredible IPv6 support', 'Direct backbone peering'],
    cons: ['Barebones', 'US jurisdiction'],
    bestFor: ['Network engineers', 'IPv6 enthusiasts'],
    worstFor: ['Users wanting threat protection'],
    verdict: "A solid, no-nonsense resolver from a company that actually builds the internet.",
    lastUpdated: '2026-06-01',
  },
  dnsforge: {
    providerId: 'dnsforge',
    editorialScore: 8.0,
    tagline: "A superb indie German ad-blocking resolver.",
    summary: "DNS Forge is highly respected in European privacy circles. It offers network-level ad-blocking hosted entirely within Germany.",
    privacyDetail: "Exceptional. Protected by strict German privacy laws and run as a transparent project.",
    performanceDetail: "Great in central Europe. Higher latency globally due to lack of extensive anycast.",
    securityDetail: "Excellent ad and tracker blocklists.",
    pros: ['German privacy laws', 'Effective ad-blocking', 'No logging'],
    cons: ['Poor performance outside Europe'],
    bestFor: ['German/EU users wanting local ad-blocking'],
    worstFor: ['North American users'],
    verdict: "A fantastic regional option that respects your privacy. If you live in the EU, give it a try.",
    lastUpdated: '2026-06-01',
  },
  switch: {
    providerId: 'switch',
    editorialScore: 7.9,
    tagline: "The Swiss academic network's public resolver.",
    summary: "SWITCH operates the Swiss academic network. Their public DNS is highly reliable and filters Swiss-identified malware.",
    privacyDetail: "Protected by Swiss law. Operated by an academic/non-profit foundation.",
    performanceDetail: "Optimized for Switzerland and Central Europe.",
    securityDetail: "Blocks malware based on SWITCH's own threat intelligence.",
    pros: ['Swiss jurisdiction', 'Academic/Non-profit trust', 'Good threat intel'],
    cons: ['Regional routing optimization only'],
    bestFor: ['Swiss residents', 'EU users wanting Swiss privacy'],
    worstFor: ['Global users needing anycast speed'],
    verdict: "An excellent, highly trusted regional resolver. Quad9's spiritual cousin.",
    lastUpdated: '2026-06-01',
  },
  comodo: {
    providerId: 'comodo',
    editorialScore: 6.8,
    tagline: "Legacy security vendor offering decent, but dated, protection.",
    summary: "Comodo Secure DNS blocks phishing and malware. It works well but has largely been superseded by Quad9 and Cloudflare in the sysadmin community.",
    privacyDetail: "US commercial vendor. Standard logging policies apply.",
    performanceDetail: "Average. Lacks the raw speed of modern anycast giants.",
    securityDetail: "Strong heritage in anti-malware, but no DNSSEC validation.",
    pros: ['Good legacy threat intelligence'],
    cons: ['No DNSSEC', 'US commercial jurisdiction', 'Slower than modern alternatives'],
    bestFor: ['Existing Comodo enterprise customers'],
    worstFor: ['Privacy advocates'],
    verdict: "It's fine, but there are faster, more private alternatives that do the exact same thing.",
    lastUpdated: '2026-06-01',
  },
  yandex: {
    providerId: 'yandex',
    editorialScore: 4.0,
    tagline: "Fast in Russia, but a massive red flag for western users.",
    summary: "Yandex is the Google of Russia. Their DNS is fast locally, but western sysadmins actively blacklist it due to geopolitical and privacy concerns.",
    privacyDetail: "Terrible for international users. Subject to Russian data retention laws and FSB oversight.",
    performanceDetail: "Great if you live in Moscow. Mediocre to poor everywhere else.",
    securityDetail: "Basic filtering available, but untrusted by western security researchers.",
    pros: ['Fast in Eastern Europe'],
    cons: ['Russian jurisdiction', 'State surveillance risks', 'Poor global routing'],
    bestFor: ['Users inside Russia trying to optimize local routing'],
    worstFor: ['Anyone outside of Russia'],
    verdict: "Unless you are physically located in Russia and require local routing optimization, avoid this entirely.",
    lastUpdated: '2026-06-01',
  }
};
